name: Update Dist Folder

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'dist/**'

jobs:
  update-dist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Commit and push dist folder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/
        git diff --quiet && git diff --staged --quiet || git commit -m "Update dist folder [skip ci]"
        git push 